name: Vanilla-Hammers
description: $description
version: '${version}'

main: net.paulem.vanillahammers.VanillaHammers
api-version: '1.21.11'
load: POSTWORLD

authors: [ Paulem ]
website: https://paulem.net

folia-supported: true