[versions]
paper-api = "1.21.11-R0.1-SNAPSHOT"
minecraft = "1.21.11"
shadow = "9.6.0"
run-task = "3.0.2"
vanilla-gradle = "0.3.2"
glowingentities = "1.4.11"
universalscheduler = "0.1.7"
arcana = "0.0.1"
lombok = "1.18.46"
packed = "1.1.4"
mcbrawls = "3.2.0"
javalin = "7.2.2"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
glowingentities = { module = "fr.skytasul:glowingentities", version.ref = "glowingentities" }
arcana = { module = "ovh.paulem:Arcana", version.ref = "arcana" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
packed = { module = "net.radstevee.packed:packed-core", version.ref = "packed" }
universalscheduler = { module = "com.github.Anon8281:UniversalScheduler", version.ref = "universalscheduler" }
mcbrawls-spigot = { module = "net.mcbrawls.inject:spigot", version.ref = "mcbrawls" }
mcbrawls-api = { module = "net.mcbrawls.inject:api", version.ref = "mcbrawls" }
mcbrawls-http = { module = "net.mcbrawls.inject:http", version.ref = "mcbrawls" }
mcbrawls-jetty = { module = "net.mcbrawls.inject:jetty", version.ref = "mcbrawls" }
mcbrawls-javalin = { module = "net.mcbrawls.inject:javalin", version.ref = "mcbrawls" }
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
vanilla-gradle = { id = "org.spongepowered.gradle.vanilla", version.ref = "vanilla-gradle" }